language: android
android:
   components:
   - tools
   - tools

jdk: oraclejdk8

os: linux
dist: trusty

sudo: required

before_script:
  - (while sleep 3; do echo "y"; done) | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "extras;android;m2repository" "extras;google;m2repository" "build-tools;26.0.0" "platforms;android-26"

script:
  - ./gradlew clean assembleDebug --stacktrace

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  -
  
  after_success:
  - bash <(curl -s https://codecov.io/bash)
  - whereis FastHub-debug.apk
  - (date +%b-%d-%Y-%H:%M)
  - cd zac6ix/FastHub/FastHub/build/outputs/apk/
  - mv FastHub-debug.apk FastHub-debug_$(date +%b-%d-%Y-%H:%M)_unofficial_C7.apk 
  - FILE=FastHub-debug_$(date +%b-%d-%Y-%H:%M)_unofficial_C7.apk
  - export FILE
  - hst=uploads.androidfilehost.com
  - us=iyke
  - key=HsHXIgOLoRXs
  - curl -ftp-pasv -T $FILE ftp://$us:$key@$hst

notifications:
  slack: fasthub:bf00ead5-f681-458b-8527-681d1faf2cf0
  email: false
 
